### ISSUE TITLE
Example error with CircuitPython 9.0.0-alpha.2

### ISSUE THREAD

**Issue by sany3001** [adafruit/Adafruit_CircuitPython_ST7565#9]
Missing file:

_Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Initializing...
Pixel test
Lines test
Rectangle test
Text test
Could not find font file font5x8.bin
Traceback (most recent call last):
  File "code.py", line 74, in <module>
  File "adafruit_framebuf.py", line 507, in text
  File "adafruit_framebuf.py", line 581, in __init__
OSError: [Errno 2] No such file/directory: font5x8.bin_

**Comment by sany3001** [comment]
Related issue: https://github.com/adafruit/Adafruit_CircuitPython_framebuf/issues/10
File must be put next to the example file.
